gen country=NAME

if country=="Albania" replace country ="Albania"
if country=="Algeria" replace country ="Algeria"
if country=="Angola" replace country ="Angola"
if country=="Antigua and Barbuda" replace country ="Antigua and Barbuda"
if country=="Argentina" replace country ="Argentina"
if country=="Armenia" replace country ="Armenia"
if country=="Australia" replace country ="Australia"
if country=="Austria" replace country ="Austria"
if country=="Azerbaijan" replace country ="Azerbaijan"
if country=="Bahamas" replace country ="Bahamas"
if country=="Bahrain" replace country ="Bahrain"
if country=="Bangladesh" replace country ="Bangladesh"
if country=="Barbados" replace country ="Barbados"
if country=="Belarus" replace country ="Belarus"
if country=="Belgium" replace country ="Belgium"
if country=="Belize" replace country ="Belize"
if country=="Benin" replace country ="Benin"
if country=="Bolivia" replace country ="Bolivia"
if country=="Botswana" replace country ="Botswana"
if country=="Brazil" replace country ="Brazil"		
if country=="Bulgaria" replace country ="Bulgaria"
if country=="Burkina Faso" replace country ="Burkina Faso"
if country=="Burundi" replace country ="Burundi"
if country=="Cambodia" replace country ="Cambodia"
if country=="Cameroon" replace country ="Cameroon"
if country=="Canada" replace country ="Canada"
if country=="Cape Verde" replace country ="Cape Verde"
if country=="Central African Republic" replace country ="Central African Republic"
if country=="Chad" replace country ="Chad"
if country=="Chile" replace country ="Chile"
if country=="China" replace country ="China"
if country=="Colombia" replace country ="Colombia"
if country=="Comoros" replace country ="Comoros"
if country=="Congo" replace country ="Congo, Rep."					
if country=="Costa Rica" replace country ="Costa Rica"
if country=="Cote d'Ivoire" replace country ="Cote d'Ivoire"
if country=="Croatia" replace country ="Croatia"
if country=="Cyprus" replace country ="Cyprus"
if country=="Czech Republic" replace country ="Czech Republic"
if country=="Democratic Republic of the Congo" replace country ="Congo, Dem. Rep."
if country=="Denmark" replace country ="Denmark"
if country=="Djibouti" replace country ="Djibouti"
if country=="Dominica" replace country ="Dominica"
if country=="Dominican Republic" replace country ="Dominican Republic"
if country=="Ecuador" replace country ="Ecuador"
if country=="Egypt" replace country ="Egypt, Arab Rep."
if country=="El Salvador" replace country ="El Salvador"
if country=="Equatorial Guinea" replace country ="Equatorial Guinea"
if country=="Eritrea" replace country ="Eritrea"
if country=="Estonia" replace country ="Estonia"
if country=="Ethiopia" replace country ="Ethiopia"
if country=="Fiji" replace country ="Fiji"
if country=="Finland" replace country ="Finland"
if country=="France" replace country ="France"
if country=="Gabon" replace country ="Gabon"
if country=="Gambia" replace country ="Gambia, The"
if country=="Georgia" replace country ="Georgia"
if country=="Germany" replace country ="Germany"
if country=="Ghana" replace country ="Ghana"
if country=="Greece" replace country ="Greece"
if country=="Guatemala" replace country ="Guatemala"
if country=="Guinea" replace country ="Guinea"
if country=="Guinea-Bissau" replace country ="Guinea-Bissau"
if country=="Guyana" replace country ="Guyana"
if country=="Haiti" replace country ="Haiti"
if country=="Honduras" replace country ="Honduras"
if country=="Hong Kong" replace country ="Hong Kong SAR, China"
if country=="Hungary" replace country ="Hungary"
if country=="Iceland" replace country ="Iceland"
if country=="India" replace country ="India"
if country=="Indonesia" replace country ="Indonesia"
if country=="Iran (Islamic Republic of)" replace country ="Iran, Islamic Rep."
if country=="Ireland" replace country ="Ireland"
if country=="Israel" replace country ="Israel"
if country=="Italy" replace country ="Italy"
if country=="Jamaica" replace country ="Jamaica"
if country=="Japan" replace country ="Japan"
if country=="Jordan" replace country ="Jordan"
if country=="Kazakhstan" replace country ="Kazakhstan"
if country=="Kenya" replace country ="Kenya"
if country=="Korea, Republic of" replace country ="Korea, Rep."
if country=="Kuwait" replace country ="Kuwait"
if country=="Kyrgyzstan" replace country ="Kyrgyz Republic"
if country=="Lao People's Democratic Republic" replace country ="		Lao, PDR"
if country=="Latvia" replace country ="Latvia"
if country=="Lebanon" replace country ="Lebanon"
if country=="Lesotho" replace country ="Lesotho"
if country=="Liberia" replace country ="Liberia"
if country=="Libyan Arab Jamahiriya" replace country ="Libya"
if country=="Lithuania" replace country ="Lithuania"
if country=="Luxembourg" replace country ="Luxembourg"
if country=="Madagascar" replace country ="Madagascar"
if country=="Malawi" replace country ="Malawi"
if country=="Malaysia" replace country ="Malaysia"
if country=="Mali" replace country ="Mali"
if country=="Mauritania" replace country ="Mauritania"
if country=="Mauritius" replace country ="Mauritius"
if country=="Mexico" replace country ="Mexico"
if country=="Mongolia" replace country ="Mongolia"
if country=="Morocco" replace country ="Morocco"
if country=="Mozambique" replace country ="Mozambique"
if country=="Namibia" replace country ="Namibia"
if country=="Nepal" replace country ="Nepal"
if country=="Netherlands" replace country ="Netherlands"					
if country=="New Zealand" replace country ="New Zealand"
if country=="Nicaragua" replace country ="Nicaragua"
if country=="Niger"	 replace country ="Niger"
if country=="Nigeria" replace country ="Nigeria"
if country=="Norway" replace country ="Norway"
if country=="Oman" replace country ="Oman"
if country=="Pakistan" replace country ="Pakistan"
if country=="Panama" replace country ="Panama"
if country=="Papua New Guinea" replace country ="Papua New Guinea"
if country=="Paraguay"	replace country ="Paraguay"
if country=="Peru" replace country ="Peru"
if country=="Philippines" replace country ="Philippines"
if country=="Poland" replace country ="Poland"
if country=="Portugal" replace country ="Portugal"
if country==" romania" replace country ="Romania"
if country==" russia"	replace country ="Russian Federation"
if country==" rwanda"	replace country ="Rwanda"
